### ISSUE TITLE
Como funciona?

### ISSUE THREAD

**Issue by ElLuigi** [ljchuello/CopyTradingIq#1]
Hola, podria indicar como realiza el copy?, en el codigo solo se conecta y recolecta informacion de las velas pero no se observa el copy de operaciones de traders

**Comment by ljchuello** [comment]
> Hola, podria indicar como realiza el copy?, en el codigo solo se conecta y recolecta informacion de las velas pero no se observa el copy de operaciones de traders

Hola, básicamente lo que hace es copiar las operaciones de una cuenta maestra, no hago nada especial acá. Utilizo la libreria de [MongkonEiadon](https://github.com/MongkonEiadon/IqOption.Net) para realizar el duplicado de las operaciones.
